In [15]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
b
print (b)
print(a.ndim)
print (a.shape)
len(a)

[1 2 3 4]
[0 1 2 3 4 5]
1
(4,)


4

In [16]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
import numpy as np
c=np.array([[[0,1,3],[2,3,4]],[[4,5,8],[6,7,9]]])
print(c)
print(c.ndim)
print(c.shape)
len(c)

[[[0 1 3]
  [2 3 4]]

 [[4 5 8]
  [6 7 9]]]
3
(2, 2, 3)


2

In [11]:
import numpy as np
a=np.linspace(0,2,6)#start,end,gap
b=np.ones((3,3))
c=np.eye(3)
d=np.eye(3,2)#row,col
e=np.diag((1,2,3,4))
f=np.random.rand(4)
g=np.random.randn(4)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

[0.  0.4 0.8 1.2 1.6 2. ]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[0.1052862  0.65261265 0.58242471 0.20414628]
[0.74064264 1.5929544  0.1510043  0.51123637]


In [21]:
import numpy as np
a=np.arange(10)
c=np.arange(10)
print(a[5])
b=np.diag([1,2,3])
print(b[2,2])
print(b[1,2])
print(a[2:5:1])
a[5:8]=10
print(a)


5
3
0
[2 3 4]
[ 0  1  2  3  4 10 10 10  8  9]


In [24]:
import numpy as np
a=np.arange(10)
b=np.arange(5)
a[5:]=b[::-1]
print(a)

[0 1 2 3 4 4 3 2 1 0]


In [28]:
import numpy as np
a=np.arange(10)
b=np.arange(5)
b=a[::2]
b
print(b)
b[0]=10
print(b)

[0 2 4 6 8]
[10  2  4  6  8]


In [3]:
import numpy as np
a=np.arange(10)
b=a[::2].copy()
print(b)
b[0]=10
print(a)
print(b)

[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


In [8]:
import numpy as np
a=np.random.randint(0,20,15)
print(a)
mask=(a%2==0)
extract_from_a=a[mask]
print(extract_from_a)
a[mask]=-1
print(a)


[12  7 18  2  5 19  6 10  9 12 15 13 16  8 18]
[12 18  2  6 10 12 16  8 18]
[-1  7 -1 -1  5 19 -1 -1  9 -1 15 13 -1 -1 -1]


In [14]:
import numpy as np
a=np.arange(0,100,20)
b=np.arange(0,20,3)
print(b)
print(a)


[ 0  3  6  9 12 15 18]
[ 0 20 40 60 80]


In [3]:
import numpy as np
a=np.array([1,2,3,4])
a**2


array([ 1,  4,  9, 16])

In [4]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [5]:
import numpy as np
a=np.diag([1,2,3,4])
print(a*a)




[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [9]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([1,2,3,5])
print(a==b
a>b

[ True  True  True False]


array([False, False, False, False])

In [12]:
import numpy as np
a=np.array([4,1,2,3,4])
print(np.log(a))
np.sin(a)

[1.38629436 0.         0.69314718 1.09861229 1.38629436]


array([-0.7568025 ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [18]:
import numpy as np
a=np.array([1,2,3,4])
print(sum(a))
print(min(a))
print(max(a))
print(a.argmin())#min index

10
1
4
0


In [21]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a.sum(axis=0))#column wise
print(a.sum(axis=1))#row wise

[4 6]
[3 7]


In [29]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([[1,2,3],[4,5,6]])
print(x.min())
print(x.std())
print(np.median(x))
print(np.median(y))
print(np.median(y,axis=0))

1
1.118033988749895
2.5
3.5
[2.5 3.5 4.5]


In [37]:
#array flattening
import numpy as np
x=np.array([[1,2],[4,5]])
print(x.ravel())
print(x)
print(x.T)
y=a.ravel()
print(y)

[1 2 4 5]
[[1 2]
 [4 5]]
[[1 4]
 [2 5]]
[1 2 3 4]


In [42]:
import numpy as np
x=np.array([[4,25,1],[8,4,5]])
b=np.sort(x)
c=np.sort(x,axis=0)#row wise
print(b)
print(c)

[[ 1  4 25]
 [ 4  5  8]]
[[ 4  4  1]
 [ 8 25  5]]


In [48]:
import numpy as np
x=np.array([[4,25,1],[8,4,5]])
y=np.array([1,5,0,2])
j=np.argsort(x)
k=np.argsort(y)
print(j)
print(k)
y[k]

[[2 0 1]
 [1 2 0]]
[2 0 3 1]


array([0, 1, 2, 5])